export const FETCH_EXAMPLE = 'FETCH_EXAMPLE';
export const API_CALL = 'API_CALL';

export const CREATE_FREE_RESPONSE = 'CREATE_FREE_RESPONSE';
export const GET_FREE_RESPONSE = 'GET_FREE_RESPONSE';
export const DELETE_FREE_RESPONSE = 'DELETE_FREE_RESPONSE';

export const CREATE_MC = 'CREATE_MC';
export const GET_MC = 'GET_MC';
export const DELETE_MC = 'DELETE_MC';

export const CREATE_SECTION = 'CREATE_SECTION';
export const GET_SECTION = 'GET_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';

export const CREATE_QUESTIONAIRE = 'CREATE_QUESTIONAIRE';
export const GET_QUESTIONAIRE = 'GET_QUESTIONAIRE';
export const DELETE_QUESTIONAIRE = 'DELETE_QUESTIONAIRE';
export const CLEAR_QUESTIONAIRE_QUEUE = 'CLEAR_QUESTIONAIRE_QUEUE';

export const ADD_QUESTION_TO_QUEUE = 'ADD_QUESTION_TO_QUEUE';
export const ADD_SECTION_TO_QUEUE = 'ADD_SECTION_TO_QUEUE';
export const CLEAR_SECTION_QUEUE = 'CLEAR_SECTION_QUEUE';

export const CREATE_USER_LINK = 'CREATE_USER_LINK';
export const GET_USER_LINK = 'GET_USER_LINK';
export const SEND_USER_LINK = 'SEND_USER_LINK';
export const FIND_LINK = 'FIND_LINK';